### ISSUE TITLE
transactionReceipt 

### ISSUE THREAD

**Issue by daveamison** [saturngod/IAPHelper#12]
When using this code:-

[[IAPShare sharedHelper].iap checkReceipt:trans.transactionReceipt AndSharedSecret:@"SECRET" onCompletion:^(NSString *response, NSError *error)

show as 'transactionReceipt' is deprecated: first deprecated in iOS 7.0

**Comment by saturngod** [comment]
yes. It's deprecated. Please use [NSData dataWithContentsOfURL:[[NSBundle mainBundle] appStoreReceiptURL]];
