### ISSUE TITLE
Getting crashed if user has retried for password for Apple id

### ISSUE THREAD

**Issue by shreeshecommstreet** [saturngod/IAPHelper#15]
Steps to regenerate :

1) Try to restore the product.
2) An pop up opens for your id and password.
3) enter wrong password.
4) Pop up opens for invalid username and password.
5) enter right password.
6) Getting crash with message

 [IAPHelper respondsToSelector:]: message sent to deallocated instance 0x15847e40

**Comment by saturngod** [comment]
It may be same problem with #9
