### ISSUE TITLE
Potential Leak Warning on Xcode 6

### ISSUE THREAD

**Issue by benmarten** [saturngod/IAPHelper#18]
I am using the latest IAPHelper Version and I see this warnings in Xcode:

![screen shot 2015-04-15 at 13 39 17](https://cloud.githubusercontent.com/assets/5960238/7157977/0f07ab4a-e375-11e4-9a2d-24038cfe97bb.png)

**Comment by benmarten** [comment]
I think the fix is easy, change:
`__bridge_retained` to `__bridge`

**Comment by saturngod** [comment]
I am using https://github.com/kamiro/SFHFKeychainUtils for Keychain. It may be problem of SFHFKeychainUtils.
