### ISSUE TITLE
empty array on line 12

### ISSUE THREAD

**Issue by easybay** [saturngod/IAPHelper#19]
Hey,
when take the example code, change the product ID and run the code, I get the error 
"[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array" on the line of the declaration of product.
Why?
Many thanks in advance

**Comment by saturngod** [comment]
Hi @easybay , can you share your code ? How did you allocated the array ?  It look like array is not allocated.

**Comment by ClickedApps** [comment]
It's the example code. Copied and paste, same error.

**Comment by saturngod** [comment]
@ClickedApps 

Look like error at

 SKProduct* product =[[IAPShare sharedHelper].iap.products objectAtIndex:0];

Did you register your product identifier at iTunes Connect ?

**Comment by saturngod** [comment]
I checked it and this error occur because you didn't register any products. So, SKProductsResponse didn't response any product.

However, example code is trying to get index 0. So, this error occur. Please register your in app purchases first.
