### ISSUE TITLE
didReceiveResponse not called after requestProductsWithCompletion with flightmode on

### ISSUE THREAD

**Issue by Japspre** [saturngod/IAPHelper#21]
First of all, thanks for this little gem, its working great

One thing I found is that the delegate method is not called after asking requestProductsWithCompletion with the device flight mode on.

This causes the completion block not to be executed

**Comment by darkndream** [comment]
Is it even possible to make an IAP with flight mode on in any real application ?

**Comment by Japspre** [comment]
No, but the point is, when there's no internet connection, the completion block is not called and the app is in an endless state.

**Comment by saturngod** [comment]
I tested and it was working fine on my code. I tested with flight mode and offline. Hmm .. that so wired .. You can did the break point , check it arrive in `- (void)paymentQueue:(SKPaymentQueue *)queue updatedTransactions:(NSArray *)transactions` function or not

**Comment by Japspre** [comment]
@saturngod: I suggest closing this bug report if you cannot reproduce it. I don't have the project anymore where I was using IAPHelper.
