### ISSUE TITLE
Latest updates breaks cocoapods

### ISSUE THREAD

**Issue by RyanCopley** [saturngod/IAPHelper#22]
Installing IAPHelper (1.0.8.1)

[!] Error installing IAPHelper
[!] /usr/bin/git clone https://github.com/saturngod/IAPHelper.git /var/folders/w5/9ps2h02j1pbcq0g9l9vdzw0w0000gn/T/d20151116-2925-ehl70h --single-branch --depth 1 --branch 1.0.8.1

Cloning into '/var/folders/w5/9ps2h02j1pbcq0g9l9vdzw0w0000gn/T/d20151116-2925-ehl70h'...
warning: Could not find remote branch 1.0.8.1 to clone.
fatal: Remote branch 1.0.8.1 not found in upstream origin

**Comment by saturngod** [comment]
Sorry, it was missing tag.  Can you try again ?

**Comment by RyanCopley** [comment]
Works, thanks!
