### ISSUE TITLE
Fix ver 1.0.8.1

### ISSUE THREAD

**Issue by PhuongNL** [saturngod/IAPHelper#25]
Please fix this version to 1.0.9 or some thing, iTunes connect does not approve this type.

**Comment by Spacelapp** [comment]
Really? Why?

**Comment by nickkuh** [comment]
Yep, having 4 separate numbers is causing submissions to Apple to fail. More details here:

http://stackoverflow.com/questions/25418798/cfbundleversion-must-be-a-period-separated-list-of-at-most-three-non-negative-in

**Comment by mzeeshanid** [comment]
I am also facing same issues.

**Comment by aiy1tm** [comment]
You can fix this by adding a small script to your Podfile:

https://libraries.io/github/Jonge/Cocoapods-frameworks-version-number-fix

**Comment by saturngod** [comment]
oh! will fix it. Sorry about that

**Comment by saturngod** [comment]
fixed
