### ISSUE TITLE
can't checkReceipt

### ISSUE THREAD

**Issue by sumlitLin** [saturngod/IAPHelper#35]
remind purchase succeed  but  checkReceipt with response code 21003
![qq20160925-0](https://cloud.githubusercontent.com/assets/13796652/18814465/ebd0a60e-8346-11e6-8cb8-4d3086f82588.png)

**Comment by sumlitLin** [comment]
Help !!!

**Comment by saturngod** [comment]
21003 - `The receipt could not be authenticated.`

I think , transactionReceipt is deprecated. 

For receipt data, please use with

```
[NSData dataWithContentsOfURL:[[NSBundle mainBundle] appStoreReceiptURL]];
```

for iOS 7 or later

**Comment by sumlitLin** [comment]
@saturngod  yes , it works! thank you !
